#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActionDetailsSourceKeybindWidget

#include "Basic.hpp"

#include "KeybindWidget_classes.hpp"
#include "FortniteUI_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ActionDetailsSourceKeybindWidget.ActionDetailsSourceKeybindWidget_C
// 0x0010 (0x08F8 - 0x08E8)
class UActionDetailsSourceKeybindWidget_C : public UKeybindWidget_C
{
public:
	TScriptInterface<class IFortGlobalActionDetailsDataSource> ActionSource;                         // 0x08E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void HandleActionSourceValueChange(class UObject* Source);
	void BindActionSourceEvents();
	void UnbindActionSourceEvents();
	void SetActionSource(TScriptInterface<class IFortGlobalActionDetailsDataSource> Value);
	void UpdateInputAction();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ActionDetailsSourceKeybindWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionDetailsSourceKeybindWidget_C")
	}
	static class UActionDetailsSourceKeybindWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionDetailsSourceKeybindWidget_C>();
	}
};
DUMPER7_ASSERTS_UActionDetailsSourceKeybindWidget_C;

}

