#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_SwampSetup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_SwampSetup.Apollo_SwampSetup_C
// 0x0020 (0x0240 - 0x0220)
class AApollo_SwampSetup_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         SwampRadius;                                       // 0x0230(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                SwampLocation;                                     // 0x0234(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Setup_Swamp();
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_Apollo_SwampSetup(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Apollo_SwampSetup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Apollo_SwampSetup_C")
	}
	static class AApollo_SwampSetup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_SwampSetup_C>();
	}
};
DUMPER7_ASSERTS_AApollo_SwampSetup_C;

}

