#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_IND_Lathe_01

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_IND_Lathe_01.Apollo_IND_Lathe_01_C
// 0x0000 (0x0BB8 - 0x0BB8)
class AApollo_IND_Lathe_01_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Apollo_IND_Lathe_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Apollo_IND_Lathe_01_C")
	}
	static class AApollo_IND_Lathe_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_IND_Lathe_01_C>();
	}
};
DUMPER7_ASSERTS_AApollo_IND_Lathe_01_C;

}

