#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Roadsign_Bear

#include "Basic.hpp"

#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Roadsign_Bear.Apollo_Roadsign_Bear_C
// 0x0000 (0x0C98 - 0x0C98)
class AApollo_Roadsign_Bear_C final : public AParent_BuildingPropActor_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Apollo_Roadsign_Bear_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Apollo_Roadsign_Bear_C")
	}
	static class AApollo_Roadsign_Bear_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Roadsign_Bear_C>();
	}
};
DUMPER7_ASSERTS_AApollo_Roadsign_Bear_C;

}

