#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Terrain_Sub_G3_f7f7b52a

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Terrain_Sub_G3_f7f7b52a.Apollo_Terrain_Sub_G3_C
// 0x0000 (0x0238 - 0x0238)
class AApollo_Terrain_Sub_G3_C final : public AFortLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Apollo_Terrain_Sub_G3_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Apollo_Terrain_Sub_G3_C")
	}
	static class AApollo_Terrain_Sub_G3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Terrain_Sub_G3_C>();
	}
};
DUMPER7_ASSERTS_AApollo_Terrain_Sub_G3_C;

}

