#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Ziplines

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Ziplines.Apollo_Ziplines_C
// 0x0000 (0x0238 - 0x0238)
class AApollo_Ziplines_C final : public AFortLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Apollo_Ziplines_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Apollo_Ziplines_C")
	}
	static class AApollo_Ziplines_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Ziplines_C>();
	}
};
DUMPER7_ASSERTS_AApollo_Ziplines_C;

}

