#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ArcticBase_Hangar_Wall_Door_B_02

#include "Basic.hpp"

#include "Parent_BuildingPropWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ArcticBase_Hangar_Wall_Door_B_02.ArcticBase_Hangar_Wall_Door_B_02_C
// 0x0000 (0x0BD0 - 0x0BD0)
class AArcticBase_Hangar_Wall_Door_B_02_C final : public AParent_BuildingPropWall_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ArcticBase_Hangar_Wall_Door_B_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ArcticBase_Hangar_Wall_Door_B_02_C")
	}
	static class AArcticBase_Hangar_Wall_Door_B_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AArcticBase_Hangar_Wall_Door_B_02_C>();
	}
};
DUMPER7_ASSERTS_AArcticBase_Hangar_Wall_Door_B_02_C;

}

