#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaReadyUpTooltipWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaReadyUpTooltipWidget.AthenaReadyUpTooltipWidget_C
// 0x0060 (0x0300 - 0x02A0)
class UAthenaReadyUpTooltipWidget_C final : public UAthenaReadyUpTooltipWidget
{
public:
	class UAthenaReadyUpTooltipTickWidget_C*      AthenaReadyUpTooltipTickWidget;                    // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaReadyUpTooltipTickWidget_C*      AthenaReadyUpTooltipTickWidget_1;                  // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaReadyUpTooltipTickWidget_C*      AthenaReadyUpTooltipTickWidget_2;                  // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaReadyUpTooltipTickWidget_C*      AthenaReadyUpTooltipTickWidget_3;                  // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaReadyUpTooltipTickWidget_C*      AthenaReadyUpTooltipTickWidget_4;                  // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaReadyUpTooltipTickWidget_C*      AthenaReadyUpTooltipTickWidget_5;                  // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaReadyUpTooltipTickWidget_C*      AthenaReadyUpTooltipTickWidget_6;                  // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaReadyUpTooltipTickWidget_C*      AthenaReadyUpTooltipTickWidget_7;                  // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Backplate;                                   // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_BackplateShadow;                             // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Tail;                                        // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageTailShadow;                                   // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaReadyUpTooltipWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaReadyUpTooltipWidget_C")
	}
	static class UAthenaReadyUpTooltipWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaReadyUpTooltipWidget_C>();
	}
};
DUMPER7_ASSERTS_UAthenaReadyUpTooltipWidget_C;

}

