#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaMatchStatusTextPlayer

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function AthenaMatchStatusTextPlayer.AthenaMatchStatusTextPlayer_C.HighlightMaterialControl
// 0x00F0 (0x00F0 - 0x0000)
struct AthenaMatchStatusTextPlayer_C_HighlightMaterialControl final
{
public:
	struct FSlateFontInfo                         NewLocalVar_0;                                     // 0x0000(0x0050)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x0050(0x0050)(HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo_1;                 // 0x00A0(0x0050)(HasGetValueTypeHash)
};
DUMPER7_ASSERTS_AthenaMatchStatusTextPlayer_C_HighlightMaterialControl;

// Function AthenaMatchStatusTextPlayer.AthenaMatchStatusTextPlayer_C.SetOpacityAndColor
// 0x0028 (0x0028 - 0x0000)
struct AthenaMatchStatusTextPlayer_C_SetOpacityAndColor final
{
public:
	struct FSlateColor                            ColorIn;                                           // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_AthenaMatchStatusTextPlayer_C_SetOpacityAndColor;

// Function AthenaMatchStatusTextPlayer.AthenaMatchStatusTextPlayer_C.GetFont
// 0x0050 (0x0050 - 0x0000)
struct AthenaMatchStatusTextPlayer_C_GetFont final
{
public:
	struct FSlateFontInfo                         Output;                                            // 0x0000(0x0050)(Parm, OutParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_AthenaMatchStatusTextPlayer_C_GetFont;

// Function AthenaMatchStatusTextPlayer.AthenaMatchStatusTextPlayer_C.SetFont
// 0x0050 (0x0050 - 0x0000)
struct AthenaMatchStatusTextPlayer_C_SetFont final
{
public:
	struct FSlateFontInfo                         FontIn;                                            // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_AthenaMatchStatusTextPlayer_C_SetFont;

// Function AthenaMatchStatusTextPlayer.AthenaMatchStatusTextPlayer_C.SetText
// 0x0020 (0x0020 - 0x0000)
struct AthenaMatchStatusTextPlayer_C_SetText final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          ApplyImmediately;                                  // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_AthenaMatchStatusTextPlayer_C_SetText;

// Function AthenaMatchStatusTextPlayer.AthenaMatchStatusTextPlayer_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct AthenaMatchStatusTextPlayer_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_AthenaMatchStatusTextPlayer_C_PreConstruct;

// Function AthenaMatchStatusTextPlayer.AthenaMatchStatusTextPlayer_C.ExecuteUbergraph_AthenaMatchStatusTextPlayer
// 0x0008 (0x0008 - 0x0000)
struct AthenaMatchStatusTextPlayer_C_ExecuteUbergraph_AthenaMatchStatusTextPlayer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_AthenaMatchStatusTextPlayer_C_ExecuteUbergraph_AthenaMatchStatusTextPlayer;

}

