#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorWeaponLoadout

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaSpectatorWeaponLoadout.AthenaSpectatorWeaponLoadout_C
// 0x0030 (0x0308 - 0x02D8)
class UAthenaSpectatorWeaponLoadout_C final : public UAthenaSpectatorQuickbarBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAthenaSpectatorInventorySlot_C*        Slot1;                                             // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorInventorySlot_C*        Slot2;                                             // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorInventorySlot_C*        Slot3;                                             // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorInventorySlot_C*        Slot4;                                             // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorInventorySlot_C*        Slot5;                                             // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_AthenaSpectatorWeaponLoadout(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaSpectatorWeaponLoadout_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaSpectatorWeaponLoadout_C")
	}
	static class UAthenaSpectatorWeaponLoadout_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaSpectatorWeaponLoadout_C>();
	}
};
DUMPER7_ASSERTS_UAthenaSpectatorWeaponLoadout_C;

}

