#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaHUD_PickupItemWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaHUD-PickupItemWidget.AthenaHUD-PickupItemWidget_C
// 0x0038 (0x02C0 - 0x0288)
class UAthenaHUD_PickupItemWidget_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAthenaItemDetailsHeader_C*             ItemDetailsHeader;                                 // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URetainerBox*                           RetainerBox_0;                                     // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class AFortPickup*                            Pickup;                                            // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UFortItem*                              PickupItem;                                        // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class AFortPickup* Pickup)> InteractionFailureText;                // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void SetPickup(class AFortPickup* NewPickup);
	void InitializeInteractionFailureText();
	void InitializeItemData();
	void Construct();
	void ExecuteUbergraph_AthenaHUD_PickupItemWidget(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaHUD-PickupItemWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaHUD-PickupItemWidget_C")
	}
	static class UAthenaHUD_PickupItemWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaHUD_PickupItemWidget_C>();
	}
};
DUMPER7_ASSERTS_UAthenaHUD_PickupItemWidget_C;

}

