#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaQuest_BGA

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AthenaQuest_BGA.AthenaQuest_BGA_C
// 0x0110 (0x08B0 - 0x07A0)
class AAthenaQuest_BGA_C : public ABuildingGameplayActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        AmbientSound;                                      // 0x07A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Root;                                              // 0x07B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   InteractCylinder;                                  // 0x07B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FString                                 RequiredCalendarEventFlag;                         // 0x07C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          bServerQuestEnabledThisMatch;                      // 0x07D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7D1[0x7];                                      // 0x07D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  BlockedPlaylistTags;                               // 0x07D8(0x0020)(Edit, BlueprintVisible)
	bool                                          TurnOn15SecDelayToTestSplitscreen;                 // 0x07F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7F9[0x7];                                      // 0x07F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UPrimitiveComponent*>            PrimitivesToHideByDefault;                         // 0x0800(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference, HasGetValueTypeHash)
	TArray<class AFortPlayerController*>          LocalPlayersThatCanInteract;                       // 0x0810(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 BVGCalendarFlag;                                   // 0x0820(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<class UPrimitiveComponent*>            PrimitivesToShowIfQuestComplete;                   // 0x0830(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference, HasGetValueTypeHash)
	TArray<class UPrimitiveComponent*>            PrimitivesToShowIfQuestInProgress;                 // 0x0840(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference, HasGetValueTypeHash)
	TArray<class AFortPlayerController*>          ServerBlockPlayersFromMultipleInteracts;           // 0x0850(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   PreRequisite_Quest_BackendName;                    // 0x0860(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UFortQuestItemDefinition*>       QuestsRequiredOnProfile;                           // 0x0868(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	class FName                                   Primary_BackendName;                               // 0x0878(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestItemDefinition*               PreRequisite_Quest;                                // 0x0880(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestItemDefinition*               Primary_Quest;                                     // 0x0888(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             SuccessSound;                                      // 0x0890(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        SuccessFX;                                         // 0x0898(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UForceFeedbackEffect*                   SuccessShakeFeedback;                              // 0x08A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTestVisuals;                                      // 0x08A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void SetPrimitiveGroupsToHide(TArray<class UPrimitiveComponent*>* PrimitivesToHideByDefault_0, TArray<class UPrimitiveComponent*>* PrimitivesToShowIfQuestComplete_0, TArray<class UPrimitiveComponent*>* PrimitivesToShowIfQuestInProgress_0);
	void HasPlayerCompletedQuestOrIsAssisting(class AFortPlayerController* FortPlayerController, class UFortQuestItemDefinition* FortQuestItemDefinition, class FName BackendName, class AFortPlayerController** FortPlayerControllerOut, class UFortQuestItemDefinition** FortQuestItemDefinitionOut, bool* bIsCompletedForSelf, bool* bIsAssisting, bool* bHasQuest);
	void OnReady_247AC0C64A00231BDF2E619647FE16C3(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags);
	void OnCurrentQuestsReady_E0574ADE46536F84066C2F877E9CCB6A(class UFortQuestManager* OwningQuestManager, bool bFoundAllQuestsOnProfile);
	void OnEventEnded_622AF7FE468E515698CC33B4AEBD8DB4(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio);
	void OnEventUpdated_622AF7FE468E515698CC33B4AEBD8DB4(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio);
	void OnEventActive_622AF7FE468E515698CC33B4AEBD8DB4(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio);
	void ReceiveBeginPlay();
	void OnMatchReady(const struct FGameplayTagContainer& PlaylistTags, bool bIsCalendarEventEnabled, bool bFoundBlockedPlaylistTags);
	void OnPlayerQuestStateKnown_Client(class AFortPlayerController* FortPlayerController, class UFortQuestItemDefinition* FortQuestItemDefinition, bool bIsCompletedForSelf, bool bIsAssisting, bool HasQuest);
	void CheckLocalPlayersCurrentQuestsReady();
	void OnPlayerCurrentQuestsReady_Client(class AFortPlayerController* FortPlayerController);
	void OnDisplayDynamicQuestUpdate(const class UFortQuestObjectiveInfo* QuestObjective, bool bDisplayStatusUpdate, bool bDisplayAnnouncementUpdate);
	void BlueprintOnInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted);
	void OnQuestEnabledForPlayer(class AFortPlayerController* FortPlayerController);
	void OnObjectiveCompleteForPlayer(class UFortQuestObjectiveInfo* ObjectiveInfo, class AFortPlayerController* PCOverrideForVisualTesting);
	void BindToQuestManagerForQuestUpdate(class AFortPlayerController* FortPlayerController);
	void OnObjectiveCompleteForPlayer_VisualTestingOverride(class UFortQuestObjectiveInfo* ObjectiveInfo, class AFortPlayerController* PCOverrideForVisualTesting);
	void ExecuteUbergraph_AthenaQuest_BGA(int32 EntryPoint);

	bool BlueprintCanInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted, const ETInteractionType InteractionType) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaQuest_BGA_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaQuest_BGA_C")
	}
	static class AAthenaQuest_BGA_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthenaQuest_BGA_C>();
	}
};
DUMPER7_ASSERTS_AAthenaQuest_BGA_C;

}

