#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaStormSurgeIconWidget

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaStormSurgeIconWidget.AthenaStormSurgeIconWidget_C
// 0x0038 (0x0298 - 0x0260)
class UAthenaStormSurgeIconWidget_C final : public UUserWidget
{
public:
	class UWidgetAnimation*                       IconDMG_Off;                                       // 0x0260(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       IconDMG_On;                                        // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Glow;                                              // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 StormIcon;                                         // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 StormIconOff;                                      // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Anim_dmgOFF();
	void Anim_dmgON();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaStormSurgeIconWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaStormSurgeIconWidget_C")
	}
	static class UAthenaStormSurgeIconWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaStormSurgeIconWidget_C>();
	}
};
DUMPER7_ASSERTS_UAthenaStormSurgeIconWidget_C;

}

