#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AutoRunHUDWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AutoRunHUDWidget.AutoRunHUDWidget_C
// 0x0010 (0x02D8 - 0x02C8)
class UAutoRunHUDWidget_C final : public UFortHUDElementWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_Run;                                         // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Destruct();
	void Construct();
	void OnAutoRunEnabled_Bind(bool bAutoRunEnabled);
	void ExecuteUbergraph_AutoRunHUDWidget(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AutoRunHUDWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AutoRunHUDWidget_C")
	}
	static class UAutoRunHUDWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAutoRunHUDWidget_C>();
	}
};
DUMPER7_ASSERTS_UAutoRunHUDWidget_C;

}

