#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Glider_MarkII

#include "Basic.hpp"

#include "B_Glider_MarkII_classes.hpp"
#include "B_Glider_MarkII_parameters.hpp"


namespace SDK
{

// Function B_Glider_MarkII.B_Glider_MarkII_C.OnParachuteTrailUpdated
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   MovementLengthSquared                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ForwardDot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   RightDot                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   RotationalMovementAcceleration                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Glider_MarkII_C::OnParachuteTrailUpdated(float MovementLengthSquared, float ForwardDot, float RightDot, float RotationalMovementAcceleration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Glider_MarkII_C", "OnParachuteTrailUpdated");

	Params::B_Glider_MarkII_C_OnParachuteTrailUpdated Parms{};

	Parms.MovementLengthSquared = MovementLengthSquared;
	Parms.ForwardDot = ForwardDot;
	Parms.RightDot = RightDot;
	Parms.RotationalMovementAcceleration = RotationalMovementAcceleration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Glider_MarkII.B_Glider_MarkII_C.Reset
// (BlueprintCallable, BlueprintEvent)

void AB_Glider_MarkII_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Glider_MarkII_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Glider_MarkII.B_Glider_MarkII_C.ExecuteUbergraph_B_Glider_MarkII
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Glider_MarkII_C::ExecuteUbergraph_B_Glider_MarkII(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Glider_MarkII_C", "ExecuteUbergraph_B_Glider_MarkII");

	Params::B_Glider_MarkII_C_ExecuteUbergraph_B_Glider_MarkII Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

