#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_HeldObject_Explosive

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BGA_HeldObject_Parent_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BGA_HeldObject_Explosive.BGA_HeldObject_Explosive_C
// 0x02C0 (0x0C40 - 0x0980)
#pragma pack(push, 0x1)
class alignas(0x10) ABGA_HeldObject_Explosive_C : public ABGA_HeldObject_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BGA_HeldObject_Explosive_C;         // 0x0980(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0988(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerController*                  LastDamageInstigator;                              // 0x0990(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HealthIsZero;                                      // 0x0998(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_999[0x3];                                      // 0x0999(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           FireCue;                                           // 0x099C(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bShouldDie;                                        // 0x09A4(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_9A5[0x3];                                      // 0x09A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             PreExplodeSound;                                   // 0x09A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           ExplosionCUE;                                      // 0x09B0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             On_Fire_Hit_Info;                                  // 0x09B8(0x008C)(Edit, BlueprintVisible, Net, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             Last_Hit;                                          // 0x0A44(0x008C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FGameplayTag                           Explosion_CUE_Water;                               // 0x0AD0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         KnockbackStrength;                                 // 0x0AD8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	class AActor*                                 CurrentPlayerToLaunch;                             // 0x0AF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  TC_Melee_Damage;                                   // 0x0B00(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Min_Duration_TnTina_Fuse;                          // 0x0B20(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Max_Duration_TnTina_Fuse;                          // 0x0B40(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Min_Duration_Damage_Fuse_;                         // 0x0B60(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Max_Duration_Damage_Fuse;                          // 0x0B80(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FVector>                        Fireball_Spawn_Vectors;                            // 0x0BA0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FScalableFloat                         SpawnedProjectileMaxSpeed;                         // 0x0BB0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         SpawnedProjectileMinSpeed;                         // 0x0BD0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         ConeHalfAngleInDegrees;                            // 0x0BF0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          CurieActivated;                                    // 0x0C10(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C11[0x7];                                      // 0x0C11(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         FireBallsToSpawn;                                  // 0x0C18(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void Server_Mismatch_Correction(const struct FVector& Actor_Location, struct FVector* Adjusted_Value);
	void Make_Local_Hit_Info(const struct FVector& Location, const struct FVector& Normal, struct FHitResult* Hit_Result);
	void OnRep_On_Fire_Hit_Info();
	bool ShouldDie(float Damage, class AController* EventInstigator, class AActor* DamageCauser);
	void OnRep_bShouldDie();
	void OnCurieActive_B5CFE25B4C5F361B8D704189B9B5BE17();
	void ReceiveBeginPlay();
	void OnDamageServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void PlayPreExplodeSound();
	void ExplodeAndDie();
	void OnDeathServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void ExplosionTrace();
	void OnDeathPlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void SetOnFire();
	void ReceiveDestroyed();
	void BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_1_OnHeldObjectPickedUp__DelegateSignature();
	void BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_2_OnHeldObjectDropped__DelegateSignature();
	void BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_3_OnHeldObjectPlaced__DelegateSignature();
	void BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_4_OnHeldObjectThrownLanded__DelegateSignature();
	void Explode_and_Die_with_Delay(class AFortPlayerController* LastDamageInstigator_0);
	void BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_0_OnHeldObjectThrown__DelegateSignature();
	void Set_Damage_Instigator_on_Throw();
	void OnCurieElementInteract_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& ElementTag, const struct FCurieInteractParamsHandle& InteractParamsHandle);
	void OnCurieElementInteractBegun_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& ElementTag, const struct FCurieInteractParamsHandle& InteractParamsHandle);
	void ExecuteUbergraph_BGA_HeldObject_Explosive(int32 EntryPoint);

	bool BlueprintCanInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted, const ETInteractionType InteractionType) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BGA_HeldObject_Explosive_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BGA_HeldObject_Explosive_C")
	}
	static class ABGA_HeldObject_Explosive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABGA_HeldObject_Explosive_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_ABGA_HeldObject_Explosive_C;

}

