#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_CurieFireMesh_TnTina

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BGA_GenericCurieFuel_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BGA_CurieFireMesh_TnTina.BGA_CurieFireMesh_TnTina_C
// 0x0008 (0x0838 - 0x0830)
class ABGA_CurieFireMesh_TnTina_C final : public ABGA_GenericCurieFuel_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BGA_CurieFireMesh_TnTina_C;         // 0x0830(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BGA_CurieFireMesh_TnTina(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BGA_CurieFireMesh_TnTina_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BGA_CurieFireMesh_TnTina_C")
	}
	static class ABGA_CurieFireMesh_TnTina_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABGA_CurieFireMesh_TnTina_C>();
	}
};
DUMPER7_ASSERTS_ABGA_CurieFireMesh_TnTina_C;

}

