#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AthenaCollectionItemToast

#include "Basic.hpp"

#include "BP_AthenaCollectionItemToast_classes.hpp"
#include "BP_AthenaCollectionItemToast_parameters.hpp"


namespace SDK
{

// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.SequenceEvent__ENTRYPOINTBP_AthenaCollectionItemToast_1
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AthenaCollectionItemToast_C::SequenceEvent__ENTRYPOINTBP_AthenaCollectionItemToast_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "SequenceEvent__ENTRYPOINTBP_AthenaCollectionItemToast_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.SequenceEvent__ENTRYPOINTBP_AthenaCollectionItemToast_0
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AthenaCollectionItemToast_C::SequenceEvent__ENTRYPOINTBP_AthenaCollectionItemToast_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "SequenceEvent__ENTRYPOINTBP_AthenaCollectionItemToast_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.ShowStars
// (BlueprintCallable, BlueprintEvent)

void UBP_AthenaCollectionItemToast_C::ShowStars()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "ShowStars");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.Play Catch Audio
// (BlueprintCallable, BlueprintEvent)

void UBP_AthenaCollectionItemToast_C::Play_Catch_Audio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "Play Catch Audio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.BP_OnToastUpdated
// (Event, Protected, BlueprintEvent)
// Parameters:
// EFortCollectedState                     CollectedState_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NumCollected                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaCollectionItemToast_C::BP_OnToastUpdated(EFortCollectedState CollectedState_0, int32 NumCollected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "BP_OnToastUpdated");

	Params::BP_AthenaCollectionItemToast_C_BP_OnToastUpdated Parms{};

	Parms.CollectedState_0 = CollectedState_0;
	Parms.NumCollected = NumCollected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.BP_OnStarRatingSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   StarRating                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaCollectionItemToast_C::BP_OnStarRatingSet(int32 StarRating)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "BP_OnStarRatingSet");

	Params::BP_AthenaCollectionItemToast_C_BP_OnStarRatingSet Parms{};

	Parms.StarRating = StarRating;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.BP_OnNormalizedLengthSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   NormalizedLength                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NormalizedMinLength                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NormalizedMaxLength                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaCollectionItemToast_C::BP_OnNormalizedLengthSet(float NormalizedLength, float NormalizedMinLength, float NormalizedMaxLength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "BP_OnNormalizedLengthSet");

	Params::BP_AthenaCollectionItemToast_C_BP_OnNormalizedLengthSet Parms{};

	Parms.NormalizedLength = NormalizedLength;
	Parms.NormalizedMinLength = NormalizedMinLength;
	Parms.NormalizedMaxLength = NormalizedMaxLength;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.BP_OnToastReset
// (Event, Protected, BlueprintEvent)

void UBP_AthenaCollectionItemToast_C::BP_OnToastReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "BP_OnToastReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.BP_OnRankSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   Rank                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NumEntries                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaCollectionItemToast_C::BP_OnRankSet(int32 Rank, int32 NumEntries)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "BP_OnRankSet");

	Params::BP_AthenaCollectionItemToast_C_BP_OnRankSet Parms{};

	Parms.Rank = Rank;
	Parms.NumEntries = NumEntries;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.ResetAnims
// (BlueprintCallable, BlueprintEvent)

void UBP_AthenaCollectionItemToast_C::ResetAnims()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "ResetAnims");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.BP_OnUnlockedNewClue
// (Event, Protected, BlueprintEvent)

void UBP_AthenaCollectionItemToast_C::BP_OnUnlockedNewClue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "BP_OnUnlockedNewClue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AthenaCollectionItemToast.BP_AthenaCollectionItemToast_C.ExecuteUbergraph_BP_AthenaCollectionItemToast
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaCollectionItemToast_C::ExecuteUbergraph_BP_AthenaCollectionItemToast(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionItemToast_C", "ExecuteUbergraph_BP_AthenaCollectionItemToast");

	Params::BP_AthenaCollectionItemToast_C_ExecuteUbergraph_BP_AthenaCollectionItemToast Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

