#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AthenaCollectionScreenInfoOverlayFishing

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_AthenaCollectionScreenInfoOverlayFishing.BP_AthenaCollectionScreenInfoOverlayFishing_C
// 0x0158 (0x0580 - 0x0428)
class UBP_AthenaCollectionScreenInfoOverlayFishing_C final : public UAthenaCollectionScreenInfoOverlayFishing
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0428(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FanFare;                                           // 0x0430(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ReloadInfo;                                        // 0x0438(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCommonActionWidget*                    Action_ShowLeaderboard;                            // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_AdditionalInfo;                             // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_ShowLeaderboard;                            // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HBox_RelativeSize;                                 // 0x0458(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                HighScore;                                         // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       HighScoreText;                                     // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Stars;                                       // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                MobileCloseButtonSpacer;                           // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 OverlayGradientDetails;                            // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 RelativeSizeMeter;                                 // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 RelativeSizePointer;                               // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   RichText_ViewAllFriends;                           // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_MaxSize;                                   // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_MinSize;                                   // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonActivatableWidgetSwitcher*       Switcher_Info;                                     // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VBox_NumCollected;                                 // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   NewRecordText;                                     // 0x04C0(0x0018)(Edit, BlueprintVisible)
	class FText                                   NewPersonalBestText;                               // 0x04D8(0x0018)(Edit, BlueprintVisible)
	struct FSlateColor                            NewPersonalBestTextColor;                          // 0x04F0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateColor                            NewRecordTextColor;                                // 0x0518(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FLinearColor                           NewPersonalBestBorderColor;                        // 0x0540(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           NewRecordBorderColor;                              // 0x0550(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   ViewAllNumFriendsTextFormat;                       // 0x0560(0x0018)(Edit, BlueprintVisible)
	float                                         RelativeSize;                                      // 0x0578(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnCollectedStateSet(EFortCollectedState CollectedState);
	void BP_OnFriendScoresUpdated(int32 NumFriendScores);
	void BP_OnHasAdditionalInfoSet(bool bHasAdditionalInfo);
	void Construct();
	void BP_OnShowLeaderboard();
	void BP_OnHideLeaderboard();
	void BP_OnInfoOverlayReset();
	void ResetAnims();
	void BP_OnItemIconLoaded(class UObject* ItemIcon);
	void BP_OnNormalizedLengthSet(float NormalizedLength, float NormalizedMinLength, float NormalizedMaxLength);
	void BP_OnStarRatingSet(int32 NumStars);
	void BndEvt__Button_ShowLeaderboard_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BP_OnFriendLeaderboardActivated();
	void BP_OnFriendLeaderboardDeactivated();
	void ExecuteUbergraph_BP_AthenaCollectionScreenInfoOverlayFishing(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AthenaCollectionScreenInfoOverlayFishing_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AthenaCollectionScreenInfoOverlayFishing_C")
	}
	static class UBP_AthenaCollectionScreenInfoOverlayFishing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AthenaCollectionScreenInfoOverlayFishing_C>();
	}
};
DUMPER7_ASSERTS_UBP_AthenaCollectionScreenInfoOverlayFishing_C;

}

