#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Demeter_Lighthouse_Prototype_Spinny_LightBeams

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Demeter_Lighthouse_Prototype_Spinny_LightBeams.BP_Demeter_Lighthouse_Prototype_Spinny_LightBeams_C
// 0x0038 (0x0BF0 - 0x0BB8)
class ABP_Demeter_Lighthouse_Prototype_Spinny_LightBeams_C final : public ABuildingProp
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BB8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   FresnelBeam_A2;                                    // 0x0BC0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   FresnelBeam_A1;                                    // 0x0BC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Cone_Length;                                       // 0x0BD0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Start_Radius;                                      // 0x0BD4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Cone_Angle;                                        // 0x0BD8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Light_Color_rgb__and_Brightness_a_;                // 0x0BDC(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Light_Shift;                                       // 0x0BEC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void initializeMaterialParams();
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_Demeter_Lighthouse_Prototype_Spinny_LightBeams(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Demeter_Lighthouse_Prototype_Spinny_LightBeams_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Demeter_Lighthouse_Prototype_Spinny_LightBeams_C")
	}
	static class ABP_Demeter_Lighthouse_Prototype_Spinny_LightBeams_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Demeter_Lighthouse_Prototype_Spinny_LightBeams_C>();
	}
};
DUMPER7_ASSERTS_ABP_Demeter_Lighthouse_Prototype_Spinny_LightBeams_C;

}

