#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_JCountdown_InGame

#include "Basic.hpp"

#include "BP_CountdownMaster_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_JCountdown_InGame.BP_JCountdown_InGame_C
// 0x0048 (0x0378 - 0x0330)
class ABP_JCountdown_InGame_C final : public ABP_CountdownMaster_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_JCountdown_InGame_C;             // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   FinalStage;                                        // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_JCountDownNew3;                                 // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_JCountDownNew;                                  // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_JCountDownNew2;                                 // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FString                                 CalendarEventName;                                 // 0x0358(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	int32                                         Stage;                                             // 0x0368(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	float                                         TwoMinuteMark;                                     // 0x036C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             CountdownFinishedSound;                            // 0x0370(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnRep_Stage();
	void OnReady_A0F7F392412AD9BCF6D9378315D177C5();
	void OnEventEnded_71FA3FEC467D9DC1C9AACAB25C9991E7(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio);
	void OnEventUpdated_71FA3FEC467D9DC1C9AACAB25C9991E7(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio);
	void OnEventActive_71FA3FEC467D9DC1C9AACAB25C9991E7(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio);
	void ReceiveBeginPlay();
	void Stage1();
	void Stage0();
	void Handle_Stage_2_Trigger(const struct FTimespan& InTimespan);
	void Start_Stage_2();
	void Stage2();
	void FinalDisplay();
	void TestFinalStage();
	void ExecuteUbergraph_BP_JCountdown_InGame(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_JCountdown_InGame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_JCountdown_InGame_C")
	}
	static class ABP_JCountdown_InGame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_JCountdown_InGame_C>();
	}
};
DUMPER7_ASSERTS_ABP_JCountdown_InGame_C;

}

