#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Button_EmoteMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Button_EmoteMenu.Button_EmoteMenu_C
// 0x0010 (0x03E0 - 0x03D0)
class UButton_EmoteMenu_C final : public UEmoteMenuButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 ExternalEmoteBang;                                 // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnHUDStateUpdate(const struct FFortHUDState& NewState);
	void ExecuteUbergraph_Button_EmoteMenu(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Button_EmoteMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Button_EmoteMenu_C")
	}
	static class UButton_EmoteMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButton_EmoteMenu_C>();
	}
};
DUMPER7_ASSERTS_UButton_EmoteMenu_C;

}

