#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cr_ChBrowserChTile

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Cr_ChBrowserChTile.Cr_ChBrowserChTile_C.Populate
// 0x0048 (0x0048 - 0x0000)
struct Cr_ChBrowserChTile_C_Populate final
{
public:
	class FText                                   InName;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   inTX;                                              // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   inRX;                                              // 0x0030(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_Cr_ChBrowserChTile_C_Populate;

// Function Cr_ChBrowserChTile.Cr_ChBrowserChTile_C.ExecuteUbergraph_Cr_ChBrowserChTile
// 0x0018 (0x0018 - 0x0000)
struct Cr_ChBrowserChTile_C_ExecuteUbergraph_Cr_ChBrowserChTile final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_MakeStruct_LinearColor;                     // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelected_ReturnValue;                  // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetSelected_ReturnValue_1;                // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_Cr_ChBrowserChTile_C_ExecuteUbergraph_Cr_ChBrowserChTile;

}

