#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortPostGameMobileOverlay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortPostGameMobileOverlay.FortPostGameMobileOverlay_C
// 0x0018 (0x02A8 - 0x0290)
class UFortPostGameMobileOverlay_C final : public UFortPostGameMobileButtonOverlay
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton_EmoteMenu_C*                    Button_EmoteMenu;                                  // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHamburgerButton_C*                     Button_HamburgerMenu;                              // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Destruct();
	void ExecuteUbergraph_FortPostGameMobileOverlay(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FortPostGameMobileOverlay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FortPostGameMobileOverlay_C")
	}
	static class UFortPostGameMobileOverlay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortPostGameMobileOverlay_C>();
	}
};
DUMPER7_ASSERTS_UFortPostGameMobileOverlay_C;

}

