#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortReplayHighlightAnnotation

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortReplayHighlightAnnotation.FortReplayHighlightAnnotation_C
// 0x0000 (0x02A0 - 0x02A0)
class UFortReplayHighlightAnnotation_C final : public UFortHighlightAnnotation
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FortReplayHighlightAnnotation_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FortReplayHighlightAnnotation_C")
	}
	static class UFortReplayHighlightAnnotation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortReplayHighlightAnnotation_C>();
	}
};
DUMPER7_ASSERTS_UFortReplayHighlightAnnotation_C;

}

