#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HighTower_HoneyDew_JumpSmash_Knockback

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Athena_Knockback_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HighTower_HoneyDew_JumpSmash_Knockback.GA_HighTower_HoneyDew_JumpSmash_Knockback_C
// 0x0010 (0x0CF0 - 0x0CE0)
class UGA_HighTower_HoneyDew_JumpSmash_Knockback_C final : public UGA_Athena_Knockback_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_HighTower_HoneyDew_JumpSmash_Knockback_C; // 0x0CE0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UClass*                                 GE_Grav;                                           // 0x0CE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_HighTower_HoneyDew_JumpSmash_Knockback(int32 EntryPoint);
	void LaunchFinished();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_HighTower_HoneyDew_JumpSmash_Knockback_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_HighTower_HoneyDew_JumpSmash_Knockback_C")
	}
	static class UGA_HighTower_HoneyDew_JumpSmash_Knockback_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HighTower_HoneyDew_JumpSmash_Knockback_C>();
	}
};
DUMPER7_ASSERTS_UGA_HighTower_HoneyDew_JumpSmash_Knockback_C;

}

