#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Athena_ReactiveProp_PropaneTank_OnFire

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_Athena_ReactiveProp_PropaneTank_OnFire.GCNL_Athena_ReactiveProp_PropaneTank_OnFire_C
// 0x0010 (0x07D0 - 0x07C0)
class AGCNL_Athena_ReactiveProp_PropaneTank_OnFire_C final : public AFortGameplayCueNotify_Loop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCurveFloat*                            SpawnRampCurve;                                    // 0x07C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnLoopingStart(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents);
	void Loop();
	void StartLoop();
	void ExecuteUbergraph_GCNL_Athena_ReactiveProp_PropaneTank_OnFire(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCNL_Athena_ReactiveProp_PropaneTank_OnFire_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCNL_Athena_ReactiveProp_PropaneTank_OnFire_C")
	}
	static class AGCNL_Athena_ReactiveProp_PropaneTank_OnFire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_Athena_ReactiveProp_PropaneTank_OnFire_C>();
	}
};
DUMPER7_ASSERTS_AGCNL_Athena_ReactiveProp_PropaneTank_OnFire_C;

}

