#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hightower_SLC_Wall_Curve_A

#include "Basic.hpp"

#include "Parent_BuildingWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Hightower_SLC_Wall_Curve_A.Hightower_SLC_Wall_Curve_A_C
// 0x0000 (0x0CC8 - 0x0CC8)
class AHightower_SLC_Wall_Curve_A_C final : public AParent_BuildingWall_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Hightower_SLC_Wall_Curve_A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Hightower_SLC_Wall_Curve_A_C")
	}
	static class AHightower_SLC_Wall_Curve_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHightower_SLC_Wall_Curve_A_C>();
	}
};
DUMPER7_ASSERTS_AHightower_SLC_Wall_Curve_A_C;

}

