#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KeybindWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass KeybindWidget.KeybindWidget_C
// 0x0000 (0x08E8 - 0x08E8)
class UKeybindWidget_C : public UFortKeybindWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("KeybindWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KeybindWidget_C")
	}
	static class UKeybindWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKeybindWidget_C>();
	}
};
DUMPER7_ASSERTS_UKeybindWidget_C;

}

