#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KillerInfoWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass KillerInfoWidget.KillerInfoWidget_C
// 0x0038 (0x03C0 - 0x0388)
class UKillerInfoWidget_C final : public UAthenaLastKillerInfoWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0388(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UKillerHealthAndShield_C*               KillerHealthAndShield;                             // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UKillerInfoWeaponWidget_C*              KillerInfoWeaponWidget;                            // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UKillerKillsWidget_C*                   KillerKillsWidget;                                 // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           KillerNameVertBox;                                 // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_KillerName;                                   // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_UserId;                                       // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetKillerName(const class FString& PlayerName, const class FString& PlayerId);
	void SetKillerWeaponIconAndName(class UTexture2D* IconTexture, const class UFortWeaponItemDefinition* ItemDef);
	void SetKillerHealthAndShield(float HealthPercent, float ShieldPercent);
	void SetNumOfKillerKills(int32 NumOfKillers);
	void ExecuteUbergraph_KillerInfoWidget(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("KillerInfoWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KillerInfoWidget_C")
	}
	static class UKillerInfoWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKillerInfoWidget_C>();
	}
};
DUMPER7_ASSERTS_UKillerInfoWidget_C;

}

