#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LiveStreamLetEmKnow

#include "Basic.hpp"


namespace SDK::Params
{

// Function LiveStreamLetEmKnow.LiveStreamLetEmKnow_C.ExecuteUbergraph_LiveStreamLetEmKnow
// 0x0018 (0x0018 - 0x0000)
struct LiveStreamLetEmKnow_C_ExecuteUbergraph_LiveStreamLetEmKnow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LiveStreamLetEmKnow_C_ExecuteUbergraph_LiveStreamLetEmKnow;

}

