#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LiveStreamHUDElement

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LiveStreamHUDElement.LiveStreamHUDElement_C
// 0x0058 (0x0340 - 0x02E8)
class ULiveStreamHUDElement_C final : public ULiveStreamHUDElement
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                BorderRoot;                                        // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                HideInstructions;                                  // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   Text_HideInstructions;                             // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               VideoPlayerSlot;                                   // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   VideoPlayerClass;                                  // 0x0310(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class ULiveStreamStandalonePlayer*            VideoPlayer;                                       // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnComplete_74112BA8413888C7EAD38CA589F3B588(class UUserWidget* UserWidget);
	void OnComplete_17963E1E4795FBCACA9C17990725A1D0(class UUserWidget* UserWidget);
	void InitializeVideoPlayer();
	void VideoPlayerReady();
	void CreateVideoPlayer();
	void DestroyVideoPlayer();
	void ExecuteUbergraph_LiveStreamHUDElement(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LiveStreamHUDElement_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LiveStreamHUDElement_C")
	}
	static class ULiveStreamHUDElement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveStreamHUDElement_C>();
	}
};
DUMPER7_ASSERTS_ULiveStreamHUDElement_C;

}

