#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Neo_StairF

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Neo_StairF.Neo_StairF_C
// 0x0000 (0x0B58 - 0x0B58)
class ANeo_StairF_C final : public ABuildingStairs
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Neo_StairF_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Neo_StairF_C")
	}
	static class ANeo_StairF_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANeo_StairF_C>();
	}
};
DUMPER7_ASSERTS_ANeo_StairF_C;

}

