#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Neo__QuarterWall_Round_Crn

#include "Basic.hpp"

#include "Parent_BuildingPropWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Neo__QuarterWall_Round_Crn.Neo__QuarterWall_Round_Crn_C
// 0x0000 (0x0BD0 - 0x0BD0)
class ANeo__QuarterWall_Round_Crn_C final : public AParent_BuildingPropWall_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Neo__QuarterWall_Round_Crn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Neo__QuarterWall_Round_Crn_C")
	}
	static class ANeo__QuarterWall_Round_Crn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANeo__QuarterWall_Round_Crn_C>();
	}
};
DUMPER7_ASSERTS_ANeo__QuarterWall_Round_Crn_C;

}

