#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Neo_StoreTrim_Str

#include "Basic.hpp"

#include "Parent_BuildingPropWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Neo_StoreTrim_Str.Neo_StoreTrim_Str_C
// 0x0000 (0x0BD0 - 0x0BD0)
class ANeo_StoreTrim_Str_C final : public AParent_BuildingPropWall_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Neo_StoreTrim_Str_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Neo_StoreTrim_Str_C")
	}
	static class ANeo_StoreTrim_Str_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANeo_StoreTrim_Str_C>();
	}
};
DUMPER7_ASSERTS_ANeo_StoreTrim_Str_C;

}

