#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Parking_Bollard

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Parking_Bollard.Parking_Bollard_C
// 0x0000 (0x0BB8 - 0x0BB8)
class AParking_Bollard_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Parking_Bollard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Parking_Bollard_C")
	}
	static class AParking_Bollard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AParking_Bollard_C>();
	}
};
DUMPER7_ASSERTS_AParking_Bollard_C;

}

