#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_ParkingBlock_2

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass S_ParkingBlock_2.S_ParkingBlock_2_C
// 0x0000 (0x0BB8 - 0x0BB8)
class AS_ParkingBlock_2_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("S_ParkingBlock_2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"S_ParkingBlock_2_C")
	}
	static class AS_ParkingBlock_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AS_ParkingBlock_2_C>();
	}
};
DUMPER7_ASSERTS_AS_ParkingBlock_2_C;

}

