#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SourdropperRoundStatusFunctionLib

#include "Basic.hpp"

#include "SourdropperRoundStatusFunctionLib_classes.hpp"
#include "SourdropperRoundStatusFunctionLib_parameters.hpp"


namespace SDK
{

// Function SourdropperRoundStatusFunctionLib.SourdropperRoundStatusFunctionLib_C.GetColor
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// EFortTeamAffiliation                    TeamAffiliation                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortSourDropperColorType               ColorType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortCreativeSourDropperRoundStatusColorDataAsset*DataAsset                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor&                    OutColor                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   bColorIsValid                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USourdropperRoundStatusFunctionLib_C::GetColor(EFortTeamAffiliation TeamAffiliation, EFortSourDropperColorType ColorType, class UFortCreativeSourDropperRoundStatusColorDataAsset* DataAsset, struct FLinearColor& OutColor, class UObject* __WorldContext, bool* bColorIsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SourdropperRoundStatusFunctionLib_C", "GetColor");

	Params::SourdropperRoundStatusFunctionLib_C_GetColor Parms{};

	Parms.TeamAffiliation = TeamAffiliation;
	Parms.ColorType = ColorType;
	Parms.DataAsset = DataAsset;
	Parms.OutColor = std::move(OutColor);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	OutColor = std::move(Parms.OutColor);

	if (bColorIsValid != nullptr)
		*bColorIsValid = Parms.bColorIsValid;
}

}

