#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_BurbankSmall_S_White

#include "Basic.hpp"

#include "TextStyle_BaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle_BurbankSmall_S_White.TextStyle_BurbankSmall_S_White_C
// 0x0000 (0x0148 - 0x0148)
class UTextStyle_BurbankSmall_S_White_C final : public UTextStyle_BaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TextStyle_BurbankSmall_S_White_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TextStyle_BurbankSmall_S_White_C")
	}
	static class UTextStyle_BurbankSmall_S_White_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_BurbankSmall_S_White_C>();
	}
};
DUMPER7_ASSERTS_UTextStyle_BurbankSmall_S_White_C;

}

