#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ValkyrieContentService

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// ScriptStruct ValkyrieContentService.ValkyrieContentServiceListInfoMeta
// 0x0020 (0x0020 - 0x0000)
struct FValkyrieContentServiceListInfoMeta final
{
public:
	class FString                                 Title;                                             // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Description;                                       // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FValkyrieContentServiceListInfoMeta;

// ScriptStruct ValkyrieContentService.ValkyrieContentServiceListInfo
// 0x0038 (0x0038 - 0x0000)
struct FValkyrieContentServiceListInfo final
{
public:
	class FString                                 ContentID;                                         // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDateTime                              Created;                                           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FValkyrieContentServiceListInfoMeta    Meta;                                              // 0x0018(0x0020)(NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FValkyrieContentServiceListInfo;

// ScriptStruct ValkyrieContentService.ValkyrieContentServiceListResults
// 0x0018 (0x0018 - 0x0000)
struct FValkyrieContentServiceListResults final
{
public:
	int32                                         Limit;                                             // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FValkyrieContentServiceListInfo> Results;                                          // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FValkyrieContentServiceListResults;

}

